name: durham
favicon: null
layout_spectrum: 0.6948985659983009
typography_spectrum: 0.9138836469501257
style: the-composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.48315436113625765
  lightness: 0.4286099465098232
  saturation: 0.0011698252055794
  rhythmicContrast: 0.6131050798576325
purpose: []
